sudo: false
language: node_js
node_js:
 - '8.12'
cache:
  directories:
  - node_modules
branches:
  only:
  - master
notifications:
  email: true
jobs:
  include:
    - stage: Installing dependencies
      script: npm install       
before_deploy: 
  - npm run predeploy
deploy:
  provider: pages
  local-dir: public
  target-branch: gh-pages
  repo: front10/get-landing-page-book
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
env:
  global:
    - secure: "Wf9zHs7DskBnNv5yp/fMmTnZ6RGnyYrhMAkHKytk1QRdQ2kb6CIopcDvSMD0eYnBKgZyPeKScdIKa+Sex3BpEUeZX7+kq70EX/eUQsWgkgA4szKKkrGnqm2mzmzoFY6+HWIudUvNqByNJf7sY50wCSOBay4ApFkeUYSC+jE5BxvUW5u1u3GdgmBiDJTEAKUBrVzZBU9Wh0mnODzysKPjRUxY32MDXvKkzkzn0aT6vZNWjypxZKFa0XiAZixy4HEt2YBULOfKFSW+fR1PMtmL1O+SjhlMI5A+9ty0uxV+42XzRFLRCyiFDNoa8n7UVeuaZImKZZyRQHwDPmxocbo5KammIgqouylAwoVdFkwquyHGp1u/Yym5bqr0kGOXqzXTgcmoeYyfdZdzfqC1YRa0a2vi5RGf1KvsgM8HKyt/NTKtdTu4wBlUhUrt3PnQEYfq34gU0phJkZ3kF/DAEDvdSXtHzwxbgP3s/kP1cjrFs6QzMczl4HIobmS4R8iFRoVqX7i2/dKUqJlL5mFkkVV9xz+KB8zvE/wxeKG8jw4YSeVJzHH+nIXUWGIy202ZMr4a3UPR7/xSEy3PaEqzfSyM6qQUQpiJns7oojMJO+YOySEVTWnOMQSdg0IjXdFm8/AtnGrkTkQ5Cd8gJ6Rk1DDyeqSbUjOJy7t15eZ16jRSv/k="